= Incremental Build Publisher


This Azure Function is responsible for bouncing incrementally built (see
link:https://github.com/jenkinsci/jep/tree/master/jep/305[JEP-305]) core and
plugin artifacts into the incrementals Maven repository (see
link:https://github.com/jenkins-infra/iep/tree/master/iep-009[IEP-9]).


[[env]]
== Environment Variables

|===
| Variable | Description

| `GITHUB_TOKEN`
| A GitHub OAuth/Personal Access Token which can be used for GitHub API queries, ideally also has access to set the `repo.status` permission.

| `JENKINS_HOST`
| A Jenkins instance (defaults to `https://ci.jenkins.io/`) to which URLs are
expected to conform.

| `INCREMENTAL_URL`
| A Maven repository which should be treated as the incrementals destination,
defaults to `https://repo.jenkins-ci.org/incrementals/`

| `ARTIFACTORY_KEY`
| An Artifactory user's API key (from the link:https://repo.jenkins-ci.org/webapp/#/profile[user profile in Artifactory])

| `PERMISSIONS_URL`
| A URL pointing to the generated repository-permissions-updater output,
defaults to
`https://ci.jenkins.io/job/Infra/job/repository-permissions-updater/job/master/lastSuccessfulBuild/artifact/json/github.index.json`

|===

=== Optional/Development Variables

|===
| Variable | Description

| `BUILD_METADATA_URL`
| URL which will serve up JSON which represents metadata about a Pipeline Run (link:https://gist.github.com/rtyler/6b601864e676d0f0735c1399e291ddf4#file-gistfile1-txt[example])

| `FOLDER_METADATA_URL`
| Same but for metadata of the repository folder.

| `ARCHIVE_URL`
| URL to a `.zip` file which represents an example release zip generated by the incrementals release tooling.
|===

== Valid Requests

This Function only supports one kind of request, and is expected to only be
called by the `buildPlugin()` step or other Jenkins Pipelines which are
publishing incrementally built artifacts into Artifactory.

[source,json]
----
{
  "build_url" : "https://ci.jenkins.io/job/structs-plugin/job/PR-36/3/
}
----

This URL is expected to be the value of a `BUILD_URL` environment variable from
Jenkins.



== Testing

Unit tests can simply be run by executing `make check` in this directory.

For acceptance testing, please set the appropriate <<env>> in a terminal and
then execute `make run` in the repository root directory.

Once the Azure Functions container has come online, requests can be sent to the
Function, for example:

[source,bash]
----
curl -i -d '{"build_url":"http://localhost:8080/job/dumb/3/"}' http://localhost:7071/api/incrementals-publisher
----
